# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

spark.sql("USE CATALOG `learn_catalog`")
spark.sql("USE SCHEMA `lean_schema`")


# COMMAND ----------

dbutils.fs.ls("/databricks-datasets/retail-org/products/")

# COMMAND ----------

dbutils.fs.ls("/databricks-datasets/retail-org/customers")

# COMMAND ----------

dbutils.fs.head("/databricks-datasets/retail-org/products/products.csv")


# COMMAND ----------

dbutils.fs.ls("/databricks-datasets/retail-org")

# COMMAND ----------

dbutils.fs.ls("dbfs:/databricks-datasets/retail-org/sales_orders/")

# COMMAND ----------

# MAGIC %sql
# MAGIC drop table learn_catalog.lean_schema.products_prepared;

# COMMAND ----------

df = spark.read.table("learn_catalog.lean_schema.sales_orders_bronze_retail_org").limit(2)

# COMMAND ----------

df.printSchema()

# COMMAND ----------

df.select("order_number", "ordered_products").show(3, truncate=False)

# COMMAND ----------

from pyspark.sql import functions as F, types as T

item_schema = T.ArrayType(T.StructType([
    T.StructField("curr",  T.StringType()),
    T.StructField("id",    T.StringType()),
    T.StructField("name",  T.StringType()),
    T.StructField("price", T.DoubleType()),
    T.StructField("qty",   T.IntegerType()),
    T.StructField("unit",  T.StringType()),
]))

df_exploded = (df
    .withColumn("ordered_products_array", F.from_json(F.col("ordered_products"), item_schema))
)
df_exploded.select(
    F.col("order_number"),
    F.col("customer_id"),
    F.col("customer_name"),
    F.col("number_of_line_items"),
    (F.when(F.col("order_datetime") != "", F.to_timestamp(F.from_unixtime(F.col("order_datetime").cast("BIGINT") / 1000)))
    .otherwise(F.lit(None))
    .alias("order_datetime")),
    #F.to_timestamp(F.from_unixtime(F.col("order_datetime")/1000)).alias("order_datetime"),
    F.col("ordered_products_array.curr").alias("curr"),
    F.col("ordered_products_array.id").alias("id"),
    F.col("ordered_products_array.name").alias("name"),
    F.col("ordered_products_array.price").alias("price"),
    F.col("ordered_products_array.qty").alias("qty"),
    F.col("ordered_products_array.unit").alias("unit"),
    ).withColumn("items",
        F.explode(F.arrays_zip(
            F.col("curr"),
            F.col("id"),
            F.col("name"),
            F.col("price"),
            F.col("qty"),
            F.col("unit")))
    ).select("order_number", "customer_id", "number_of_line_items", "order_datetime", "items.curr", "items.id",  "items.price", "items.qty", "items.unit").show(10, False)

# COMMAND ----------

df_exploded.show()

# COMMAND ----------

df_customer = spark.read.table("learn_schema.customers_")
df_products = spark.read.table("learn_schema.products")

# COMMAND ----------


dfp = spark.read.table("products_bronze_retail_org")
dfp.select(
    "product_id", 
    "product_category", 
    "product_name", 
    F.round(F.col("sales_price").cast("double"), 2).alias("sales_price"),
    "EAN13", "EAN5", "product_unit").show(10, False)


# COMMAND ----------

from pyspark.sql.functions import *
spark.sql("USE CATALOG `learn_catalog`")
spark.sql("USE SCHEMA `lean_schema`")
df = spark.read.table("customer_bronze_retail_org")

# COMMAND ----------



# COMMAND ----------

df.select(
    col("customer_id").alias("customer_id"), 
    col("customer_name").alias("customer_name"),
    col("tax_code").alias("tax_code"),
    regexp_replace(col("tax_id"),r"\.0$","").alias("tax_id"),
    col("state").alias("state"),
    col("city").alias("city"),
    regexp_replace(col("postcode"),r"\.0$","").alias("postcode"),
    col("street").alias("street"),
    regexp_replace(col("number"),r"\.0$","").alias("number"),
    col("unit").alias("unit"),
    col("region").alias("region"),
    when(
        col("valid_from") != "", 
        to_timestamp(from_unixtime(col("valid_from").cast("BIGINT") / 1000))
        ).otherwise(lit(None)).alias("valid_from"),
    
    when(
        col("valid_to") != "", 
        to_timestamp(from_unixtime(regexp_replace(col("valid_to"),r"\.0$","").cast("BIGINT").cast("BIGINT") / 1000))
        ).otherwise(lit(None)).alias("valid_to"),
    col("loyalty_segment").alias("loyalty_segment")
    ).show()

# COMMAND ----------

c = spark.read.table("customers_prepared").alias("c")
p = spark.read.table("products_prepared").alias("p")
s = spark.read.table("sales_orders_prepared").alias("s")
df = (
    c.join(s , c.customer_id == s.customer_id, how="left")
    .join(p, s.id == p.product_id, how="left")
)
display(df)
# df_cust_sales = df_cust.join(df_sales, df_sales.customer_id == df_cust.customer_id, how="left")
# df_cust_sales_prod = df_cust_sales.join(df_prod, df_prod.product_id == df_cust_sales.id, how="left")
# display(df_cust_sales_prod.select(
#     col("order_number"),
#     col("order_datetime"),
#     col("df_cust.customer_id"),
#     col("df_cust.customer_name"),
#     concat_ws(" ", col("street"), col("number"), col("df_cust.unit")).alias("address"),
#     col("postcode"),
#     col("city"),
#     col("state"),
#     col("tax_id"),
#     col("tax_code"),
#     col("loyalty_segment"),
#     col("id").alias("product_id"),
#     col("name").alias("product_name"),
#     col("curr").alias("currency"),
#     col("sales_price").alias("sales_price"),
#     col("qty").alias("units_purchased"),
#     (col("sales_price") * col("qty")).alias("total_value")
#     ))

# COMMAND ----------

display(
    df.select(
        col("order_number"),
        col("order_datetime"),
        col("c.customer_id"),
        col("c.customer_name"),
        concat_ws(", ", col("street"), col("number"), col("c.unit")).alias("address"),
        col("postcode"),
        col("city"),
        col("state"),
        col("tax_id"),
        col("tax_code"),
        col("loyalty_segment"),
        col("id").alias("product_id"),
        col("name").alias("product_name"),
        col("curr").alias("currency"),
        col("sales_price").alias("sales_price"),
        col("qty").alias("units_purchased"),
        (col("sales_price") * col("qty")).alias("total_value")
    )
)

# COMMAND ----------


